//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelimundoExamenes
{
    using System;
    using System.Collections.Generic;
    
    public partial class catMateriaTemaPreguntaRespuestaBitacora
    {
        public int MateriaTemaPreguntaRespuestaBitacoraID { get; set; }
        public Nullable<int> MateriaTemaPreguntaRespuestaID { get; set; }
        public Nullable<System.Guid> UsuarioID { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<int> MateriaTemaPreguntaID { get; set; }
    }
}
